import {
  BiEyeFill,
  BiEyeSlashFill,
  RiUserAddFill,
  RiUserSharedFill,
  LaCatSolid,
  IoPaw,
  RiLogoutCircleRLine,
  RiUserFill,
  BiMoonFill,
  BiSunFill,
  FaCloudUploadAlt,
  FaSpinner,
  MdSendRound,
  FaRegularSmile,
  LaUsersSolid,
} from 'oh-vue-icons/icons';

export default [
  BiEyeFill,
  BiEyeSlashFill,
  RiUserAddFill,
  RiUserSharedFill,
  LaCatSolid,
  IoPaw,
  RiLogoutCircleRLine,
  RiUserFill,
  BiMoonFill,
  BiSunFill,
  FaCloudUploadAlt,
  FaSpinner,
  MdSendRound,
  FaRegularSmile,
  LaUsersSolid,
];
